services:
  valkey:
    image: valkey/valkey:alpine
    ports:
      - "6379:6379"
    networks:
      - l2_network

  l2-server:
    build: ./cpp/l2-server
    ports:
      - "3000:3000"
    depends_on:
      - valkey
    networks:
      - l2_network

  l2-proxy:
    build: ./cpp/l2-proxy
    ports:
      - "8888:8888"
    depends_on:
      - valkey
    networks:
      - l2_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.l2proxy.rule=Host(`localhost`)"
      - "traefik.http.routers.l2proxy.entrypoints=websecure"
      - "traefik.http.routers.l2proxy.service=l2proxy"
      - "traefik.http.services.l2proxy.loadbalancer.server.port=8888"

  l2-worker:
    build: ./cpp/l2-worker
    depends_on:
      - valkey
      - l2-server
    networks:
      - l2_network

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - valkey
    environment:
      - RIPORT=5540
    networks:
      - l2_network

  traefik:
    image: traefik:v3.1
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
    depends_on:
      - l2-proxy
    networks:
      - l2_network

networks:
  l2_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
