services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  l2-server:
    build: ./cpp/l2-server
    ports:
      - "3000:3000"
    depends_on:
      - redis

  l2-proxy:
    build: ./cpp/l2-proxy
    ports:
      - "8080:8080"
    depends_on:
      - redis

  l2-worker:
    build: ./cpp/l2-worker
    depends_on:
      - redis
      - l2-server
