services:
  valkey:
    image: valkey/valkey:alpine
    ports:
      - "6379:6379"
    networks:
      - l2_network

  l2-server:
    build: ./cpp/l2-server
    ports:
      - "3000:3000"
    depends_on:
      - valkey
    networks:
      - l2_network

  l2-proxy:
    build: ./cpp/l2-proxy
    ports:
      - "8888:8888"
    depends_on:
      - valkey
    networks:
      - l2_network

  l2-worker:
    build: ./cpp/l2-worker
    depends_on:
      - valkey
      - l2-server
    networks:
      - l2_network

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - valkey
    environment:
      - RIPORT=5540
    networks:
      - l2_network

networks:
  l2_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
